config/routes.rb
OmniMulti::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", omniauth_callbacks: "omniauth_callbacks" }
  get 'new_authorization', to: 'welcome#new_auth'
  resources :accounts
  root 'welcome#index'
  get 'pricing', to: 'welcome#pricing'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  
  validates :owner, presence: true
  validates :name, presence: true

  accepts_nested_attributes_for :owner
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_one :owned_account, class_name: 'Account', foreign_key: 'owner_id'
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
  
  def password_required?
    super && provider.blank?
  end
  
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def new
    @account = Account.new(plan: params[:plan])
    unless current_user
      @account.build_owner
      if session["devise.user_attributes"]
        @account.owner.provider = session["devise.user_attributes"]["provider"]
        @account.owner.uid = session["devise.user_attributes"]["uid"]
      end
    end
  end

  def create
    @account = Account.new(account_params)
    @account.owner_id = current_account.owner_id if current_user
    if @account.save
      user = User.find(@account.owner_id)
      sign_in user
      redirect_to root_path, notice: 'Successfully Created Account!'
    else
      render action: 'new'
    end
  end
  
  def edit
    @account = current_account
  end
  
  def update
    @account = current_account
    respond_to do |format|
      if @account.update_attributes(account_params)
        format.html { redirect_to edit_account_path(@account), notice: 'Settings were successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
    def account_params
      params.require(:account).permit(:owner_id, :name, :plan, :email, :phone, :address, :time_zone, owner_attributes: [:account_id, :first_name, :last_name, :provider, :uid, :email, :password, :password_confirmation])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :provder, :uid, :password, :current_password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
  end
  
  private

  def current_account
    Account.find_by_owner_id(current_user.id)
  end
  helper_method :current_account
  
  def verify_account
    if !current_account
      flash[:alert] = "You must create or be added to an account to access this page."
      redirect_to root_path
    end
  end
  
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user =  User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    elsif current_user
      current_user.update_attributes(uid: user.uid, provider: user.provider)
      redirect_to edit_user_registration_path, notice: "You can now sign-in with Twitter!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_authorization_path, notice: "We don't have an account associated with this twitter!"
    end
  end
  alias_method :twitter, :all
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def pricing
  end
  
  def new_auth
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    title == "" ? "Multi" : title
  end
  
  def flash_class(type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/accounts/edit.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <%= render 'layouts/error' %>
    <h2>Edit Account Settings</h2>
    <%= form_for(@account, builder: BasicFormBuilder) do |f| %>
      <%= f.text_field :name, label: "Company Name", autofocus: true %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %> 
  </div>
</div>

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
    <div class="page-header">
      <%= render 'layouts/error' %>
      <h2>Try the <%=@account.plan.capitalize %> Plan</h2>
      <h2>Free for a 30 Day Trial</h2>
    </div>

    <%= form_for @account, builder: BasicFormBuilder do |f| %>
      
      <%= f.hidden_field :plan, value: @account.plan %>
          <%= f.text_field :name, label: "Your Company or Organization", autofocus: true %>

      <% unless current_user %>
        <%= f.fields_for :owner do |o| %>
            <%= o.hidden_field :provider, value: @account.owner.provider %>
            <%= o.hidden_field :uid, value: @account.owner.uid %>
            <%= o.text_field :first_name, label: "First Name" %>
            <%= o.text_field :last_name, label: "Last Name" %>
            <%= o.text_field :email %>
            <% if o.object.password_required? %>
              <%= o.password_field :password %>
              <%= o.password_field :password_confirmation %>
            <% end %>
        <% end %>
      <% end %>

      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_error.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= flash_class type%>">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Omni-Multi', root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
        <%= render "layouts/navbar_right" %> 
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_navbar_right.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li><%= link_to "Logged in as " + current_user.email, edit_user_registration_path %></li></li>
    <li><%= link_to "Settings", edit_account_path(current_account) %></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign Up", new_account_path(:plan => 'gold') %></li>
    <li><%= link_to "Pricing", pricing_path %></li>
    <li><%= link_to "Login", new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= yield :scripts %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<%= render 'layouts/error' %>
<h1>Omni Multi Application</h1>

app/views/welcome/new_auth.html.erb
<%= render 'layouts/error' %>
<h1>
  <%= "New #{(session["devise.user_attributes"]['provider']).capitalize} Account" %>
</h1>
<p>
  <%= "We have't had anyone log in with this #{(session["devise.user_attributes"]['provider']).capitalize} Account before." %>
</p>
<p>Do you want to:</p>
<%= link_to "Create a new Account", pricing_path, class: 'btn btn-primary btn-lg' %>
<%= link_to "Add it your existing Account", edit_user_registration_path, class: 'btn btn-primary btn-lg' %>

app/views/welcome/pricing.html.erb
<% provide(:title, 'Pricing') %>
<div id="welcome" class="hero-unit span7">
  <h1>Pricing</h1>
  <h3>Build a successful subscription site.</h3>
</div>
<div class="col-md-12 plans">
  <div class="col-md-4 well">
    <div class="plan"><h2>Silver</h2></div>
    <ul class="unstyled">
      <li>Up to 2 users</li>
      <li>Unlimited Clients</li>
      <li>Unlimited Invoices</li>
    </ul>
    <h3>$9/month</h3>
    <%= link_to 'Start Free Trial', new_account_path(:plan => 'silver'), :class => 'btn btn-primary' %> 
  </div>
  <div class="col-md-4 well featured">
    <div class="plan featured-plan"><h2>Gold</h2></div>
    <ul class="unstyled">
      <li>Up to 10 users</li>
      <li>Unlimited Clients</li>
      <li>Unlimited Invoices</li>
    </ul>
    <h3>$19/month</h3>
    <%= link_to 'Start Free Trial', new_account_path(:plan => 'gold'), :class => 'btn btn-primary' %> 
  </div>
  <div class="col-md-4 well">
    <div class="plan"><h2>Platinum</h2></div>
    <ul class="unstyled">
      <li>Up to 20 users</li>
      <li>Unlimited Clients</li>
      <li>Unlimited Invoices</li>
    </ul>
    <h3>$29/month</h3>
    <%= link_to 'Start Free Trial', new_account_path(:plan => 'platinum'), :class => 'btn btn-primary' %> 
  </div>
</div>